# Generated by Django 2.2.6 on 2019-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191006_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
